### ISSUE TITLE
Cortex Peripherals and Registers Pane wont open while debugging

### ISSUE THREAD

**Issue by ali80** [damogranlabs/VS-Code-STM32-IDE#4]
I cant figure out if there is a bug with cortex-debug extension or there is something wrong with the configurations.
here is what is working
- enters debugging
- can add breakpoints
- can add watch variables

what is not working
- cortex peripheral pane wont open
- cortex registers pane wont open

I tried checking the svd file with Keil and the debugging works fine there using the same SVD file,
here is the launch.json file
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Cortex debug",
            "type": "cortex-debug",
            "request": "launch",
            "servertype": "openocd",
            "cwd": "${workspaceFolder}",
            "executable": "E:/temp/ARM/NUCLEO-F446/vsCodeTest/build/vsCodeTest.elf",
            "svdFile": "C:/Keil_v5/ARM/PACK/Keil/STM32F4xx_DFP/2.13.0/CMSIS/SVD/STM32F446x.svd",
            "configFiles": [
                "D:/STMicroelectronics/GNU-MCU-Eclipse/OpenOCD/0.10.0-10-20181020-0522/scripts/interface/stlink.cfg",
                "D:/STMicroelectronics/GNU-MCU-Eclipse/OpenOCD/0.10.0-10-20181020-0522/scripts/target/stm32f4x.cfg"
            ]
        },
        {
            "name": "Debug current Python file",
            "type": "python",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```
![screenshot of peripheral and register panes wont open](https://user-images.githubusercontent.com/6554605/48469936-47b00a80-e805-11e8-943a-8a934fe42796.png)

**Comment by schperplata** [comment]
Yeah, I am also experiencing strange things with VS Code lately. 
I have a working STM32F0x: core and peripheral tabs are working OK. Breakpoint and call stack also. 
However, I am unable to switch between different tabs while the core is halted and I keep getting "Error: _"Cannot read property 'getTreeNode' of null"_ error after latest update. 

I have downloaded SVD file (STM32F446x.svd) and tested it with my STM32F0 board: Cortex tabs are still available, and while peripheral registers are not correct (obviously), they are displayed correctly. 

Even with no SVD file defined in Launch configuration, Cortex tabs are shown:
![image](https://user-images.githubusercontent.com/8736111/48499188-261c4680-e838-11e8-88f8-2999ed0bc5c6.png)

So, my guess is there is something wrong with your VS Code or Cortex debug plugin. Try standard procedure: disable all unnecessary plugins and enable them one by one to see if other plugings interfere with Cortex Debug plugin.

So, try disabling plugins, try reinstall and than report issue on the appropriate place. I don't think this has anything to do with this scripts, since Cortex-debug configuration here is really as basic as it gets.
